### ISSUE TITLE
Text splitting regex and word regex are swapped when adding a new language

### ISSUE THREAD

**Issue by threddast** [theiceshelf/trunk#1]
### Description
I'm learning Norwegian, so I tried to add it as a new language. To do this, I just copied the regexps for Swedish and everything seems fine on the settings page, a sample text is split correctly. However, when I add the same text through _Create Text_, the entire text is recognized as one single word

#### EDIT
I figured out the problem: when adding a new language what is inserted in the "text splitting regex" box is saved as the word regex and vice-versa

### To reproduce
1. Add Norwegian as a new language
![image](https://user-images.githubusercontent.com/10909886/170862745-fc7d5a12-2a7b-4135-b50a-0075088d8f91.png)
2. Create a new text
![image](https://user-images.githubusercontent.com/10909886/170862809-7a9c3968-2f05-4671-b08d-8c9dbfec758a.png)
3. Read the text
![image](https://user-images.githubusercontent.com/10909886/170862816-d1a3a46f-2770-4011-ad08-bdb980824197.png)

### Expected behavior
Words are split correctly, the same text when practicing Spanish is parsed correctly
![image](https://user-images.githubusercontent.com/10909886/170862865-be5e0ebe-4535-4f83-9918-d43d752a3127.png)

**Comment by teesloane** [comment]
> I figured out the problem: when adding a new language what is inserted in the "text splitting regex" box is saved as the word regex and vice-versa

I'm not sure I understand this, but on looking back at the copy I used, "text splitting regex" is maybe not the most clear!
It sounds like your issue is resolved? If so, can I close this?

**Comment by threddast** [comment]
I'm sorry, I wasn't very clear

This is when I add a language:
![image](https://user-images.githubusercontent.com/10909886/170887279-b382a86d-c1db-4c08-ae1f-81f865406ca3.png)

And this is how the language is saved:
![image](https://user-images.githubusercontent.com/10909886/170887915-a25b6119-fc84-4bcc-9698-2c281c65d7c2.png)

As you see, the entries get swapped

**Comment by teesloane** [comment]
Oh, gotcha. Thanks! I will look into that and fix that for the next release.
