### ISSUE TITLE
dark theme for translation window

### ISSUE THREAD

**Issue by mbpowers** [theiceshelf/trunk#8]
Thoughts on adding toggle dark theme based on system preferences for the translation window?

I am not familiar with clojure but I have found that darkreader can be used with electron by installing with npm and should work. https://github.com/darkreader/darkreader/discussions/7204 

Awesome project !

**Comment by teesloane** [comment]
Hi! Glad you like the project! I'm not currently maintaining this project so feel free to fork it to try and add darkreader — sounds cool!
